# Required Variables
API_ID = 12345678
API_HASH = "your_api_hash"
BOT_TOKEN = "your_bot_token"
DATABASE_URL = "your_mongodb_url"
OWNER_ID = 123456789
UPSTREAM_REPO = "https://github.com/ImKrishana/Poster-Scraper-Bot"
UPSTREAM_BRANCH = "main"

# Optional Variables
AUTHORIZED_CHATS = ""
AUTHOR_NAME = "TheZake"
AUTHOR_URL = "https://t.me/TheZake"
BASE_URL = ""
BASE_URL_PORT = 80
CMD_SUFFIX = ""
CONCURRENT_CPU_TASKS = 1
DEFAULT_LANG = "en"
POSTER_API_URL = "https://thezakeapi.vercel.app"
POSTER_API_TOKEN = "thezake"
PROTECTED_API = ""
PUBLIC_MODE = True
SUDO_USERS = ""
SET_COMMANDS = True
TG_PROXY = None
TIMEZONE = "Asia/Kolkata"
UPDATE_PKGS = True
VERIFY_TIMEOUT = 0
